plugin:
  name: custom-data-type-gnd
  version: 1.5
  url: https://github.com/programmfabrik/fylr-plugin-custom-data-type-gnd
  displayname:
    de-DE: gnd-Verknüpfung
    en-US: gnd-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit der Gemeinsamen Normdatei (GND) her.
    en-US: Use for references to entities of the Integrated Authority File (GND)
  server:
    api-version:
      require: 1
  l10n: l10n/customDataTypeGND.csv
  webfrontend:
    url: customDataTypeGND.js
    css: customDataTypeGND.css
    dependencies:
      - commons-library
    
base_url_prefix: "webfrontend"
    
custom_types:
  gnd:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
      conceptAncestors:
        type: text
      conceptGeoJSON:
        type: geo_json
      facetTerm:
        type: text_l10n
    config:
      schema:
        - name: add_differentiatedpersons
          parameters:
            value:
              type: bool
        - name: add_coorporates
          parameters:
            value:
              type: bool
        - name: add_geographicplaces
          parameters:
            value:
              type: bool
        - name: add_subjects
          parameters:
            value:
              type: bool
        - name: add_works
          parameters:
            value:
              type: bool
        - name: add_conferenceorevent
          parameters:
            value:
              type: bool
        - name: exact_types
          parameters:
            value:
              type: select
              options: ["ALLE","SubjectHeadingSensoStricto","HistoricSingleEventOrEra","GroupOfPersons","CharactersOrMorphemes","MeansOfTransportWithIndividual_name","FictiveTerm","NomenclatureInBiologyOrChemistry","ProductNameOrBrandName","SoftwareProduct","Language","EthnographicName","MeansOfTransportWithIndividualName","ReligiousTerritory","NaturalGeographicUnit","TerritorialCorporateBodyOrAdministrativeUnit","FictivePlace","BuildingOrMemorial","Country","AdministrativeUnit","ExtraterrestrialTerritory","MemberState","WayBorderOrLine","NameOfSmallGeographicUnitLyingWithinAnotherGeographicUnit","FictiveCorporateBody","OrganOfCorporateBody","ProjectOrProgram","Pseudonym","LiteraryOrLegendaryCharacter","Spirits","RoyalOrMemberOfARoyalHouse","CollectivePseudonym","Gods"]
        - name: mapbox_api_key
          parameters:
            value:
              type: text
      mask:
        - name: editor_display
          parameters:
            value:
              type: select
              options: ["default", "condensed"]
    update:
      plugin_user:
        reference: system:root
      exec:
        service: "node"
        commands:
          - prog: "node"
            stdin:
              type: body
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/updater/gndUpdater.js"
              - type: "value"
                value: "%info.json%"
      timeout: 60
      batch_size: 1
      expires_days: 1              
              
base_config:
  - name: update_gnd
    group: update_custom_data_type
    parameters:
      restrict_time:
        type: bool
        default: false
        position: 0
      from_time:
        type: int
        default: 19
        min: 0
        max: 24
        position: 1
      to_time:
        type: int
        default: 4
        min: 0
        max: 24
        position: 2
      default_language:
        type: text
        default: 'de'
        position: 3
  - name: fulltext_gnd
    group: include_in_fulltext_search
    parameters:
      oldAuthorityNumber:
        type: bool
        default: true
        position: 1
      gndSubjectCategory:
        type: bool
        default: true
        position: 2
      variantName:
        type: bool
        default: true
        position: 3
      biographicalOrHistoricalInformation:
        type: bool
        default: true
        position: 4
      dateOfEstablishment:
        type: bool
        default: true
        position: 5
      dateOfPublication:
        type: bool
        default: true
        position: 6
      dateOfBirth:
        type: bool
        default: true
        position: 7
      dateOfProduction:
        type: bool
        default: true
        position: 8
      dateOfDeath:
        type: bool
        default: true
        position: 9
      dateOfTermination:
        type: bool
        default: true
        position: 10
      author:
        type: bool
        default: true
        position: 11
      firstAuthor:
        type: bool
        default: true
        position: 12
      organizerOrHost:
        type: bool
        default: true
        position: 13
      gender:
        type: bool
        default: true
        position: 14
      placeOfEvent:
        type: bool
        default: true
        position: 15
      placeOfBirth:
        type: bool
        default: true
        position: 16
      placeOfDeath:
        type: bool
        default: true
        position: 17
      placeOfBusiness:
        type: bool
        default: true
        position: 18
      associatedPlace:
        type: bool
        default: true
        position: 19
      topic:
        type: bool
        default: true
        position: 20
      predecessor:
        type: bool
        default: true
        position: 21
      precedingCorporateBody:
        type: bool
        default: true
        position: 22
      isA:
        type: bool
        default: true
        position: 23
      composer:
        type: bool
        default: true
        position: 24
      relatedWork:
        type: bool
        default: true
        position: 25
      relatedPerson:
        type: bool
        default: true
        position: 26
      precedingPlaceOrGeographicName:
        type: bool
        default: true
        position: 27
      hierarchicalSuperiorOfTheCorporateBody:
        type: bool
        default: true
        position: 28
      broaderTermInstantial:
        type: bool
        default: true
        position: 29
      broaderTermGeneral:
        type: bool
        default: true
        position: 30
      professionOrOccupation:
        type: bool
        default: true
        position: 31
      architect:
        type: bool
        default: true
        position: 32
      opusNumericDesignationOfMusicalWork:
        type: bool
        default: true
        position: 33
      definition:
        type: bool
        default: true
        position: 34
      succeedingCorporateBody:
        type: bool
        default: true
        position: 35
      succeedingPlaceOrGeographicName:
        type: bool
        default: true
        position: 36
        